medical_raw_data <- read.csv("E:/medical_raw_data.csv", header=TRUE)
View(medical_raw_data)
str(medical_raw_data)
install.packages("tidyverse")
library(tidyverse)
colSums(is.na(medical_raw_data))
library(ggplot2)
hist(medical_raw_data$Age)
hist(medical_raw_data$Children)
hist(medical_raw_data$Income)
hist(medical_raw_data$Initial_days)
medical_raw_data$Age[is.na(medical_raw_data$Age)]<-median (medical_raw_data$Age, na.rm=TRUE)
medical_raw_data$Children[is.na(medical_raw_data$Children)]<-median(medical_raw_data$Children,na.rm=TRUE)
medical_raw_data$Income[is.na(medical_raw_data$Income)]<-median(medical_raw_data$Income,na.rm=TRUE)
medical_raw_data$Initial_days[is.na(medical_raw_data$Initial_days)]<-median(medical_raw_data$Initial_days,na.rm=TRUE)
hist(medical_raw_data$Age)
hist(medical_raw_data$Children)
hist(medical_raw_data$Income)
hist(medical_raw_data$Initial_days)
medical_raw_data$Anxiety<-replace(medical_raw_data$Anxiety, is.na(medical_raw_data$Anxiety), mode(medical_raw_data$Anxiety))
medical_raw_data$Overweight<-replace(medical_raw_data$Overweight, is.na(medical_raw_data$Overweight), mode(medical_raw_data$Overweight))
medical_raw_data$Soft_drink<-replace(medical_raw_data$Soft_drink, is.na(medical_raw_data$Soft_drink), mode(medical_raw_data$Soft_drink))
colSums(is.na(medical_raw_data))
medical_raw_data$Income_z<-scale(x=medical_raw_data$Income)
head(medical_raw_data$Income_z)
hist(medical_raw_data$Income_z)
b<-boxplot(medical_raw_data$Income)
install.packages("plyr")
unique(medical_raw_data$Education)
unique(medical_raw_data$Employment)
unique(medical_raw_data$Marital)
unique(medical_raw_data$Gender)
unique(medical_raw_data$ReAdmis)
edu.num<-revalue(x=medical_raw_data$Education, replace= c("No schooling completed"=0,"Doctorate Degree"=18,"Master's Degree"=17, "GED or Alternative Credential"=10,"Professional School Degree"=13,"9th Grade to 12th Grade,No Diploma"=11,"Bachelor's Degree"=16, "Some College,1 or More Years,No Degree"=13,"Associate's Degree"=14,"Nursery School to 8th Grade"=8,"Regular High School Diploma"=12,"Some College,Less than 1 Year"=13 )
                 medical_raw_data$Education_numeric<-as.numeric(levels(edu.num))[edu.num]               
                 edu.num<-revalue(x=medical_raw_data$Education, replace= c("No Schooling Completed"=0, "Doctorate Degree"=18, "Master's Degree"=17, "GED or Alternative Credential"=10,"Professional School Degree"=13, "9th Grade to 12th Grade, No Diploma"=11, "Bachelor's Degree"=16, "Some College, 1 or More Years, No Degree"=13, "Associate's Degree"=14,"Nursery School to 8th Grade"=8,"Regular High School Diploma"= 12,"Some College, Less than 1 Year"=13 )                 
                                  medical_raw_data$Education_numeric<-as.numeric(edu.num)                               
                                  edu.num<-revalue(x=medical_raw_data$Education, replace=c("No Schooling Completed"= 0, "GED or Alternative Credential"=1, "9th Grade to 12th Grade, No Diploma"=11, "Nursery School to 8th Grade"=8, "Regular High School Diploma"=12, "Some College, Less than 1 Year"=13, "Some College, 1 or More Years, No Degree"=13, "Professional School Degree"=13, "Associate's Degree"=14, "Bachelor's Degree"=16, "Master's Degree"=18, "Doctorate Degree"=20))                                 
library(plyr)
install.packages("plyr")                                  
install.packages(deplyr)
library(plyr)
library(deplyr)
install.packages("dplyr")
library(dplyr)
edu.num<-revalue(x=medical_raw_data$Education, replace=c("No Schooling Completed"= 0, "GED or Alternative Credential"=1, "9th Grade to 12th Grade, No Diploma"=11, "Nursery School to 8th Grade"=8, "Regular High School Diploma"=12, "Some College, Less than 1 Year"=13, "Some College, 1 or More Years, No Degree"=13, "Professional School Degree"=13, "Associate's Degree"=14, "Bachelor's Degree"=16, "Master's Degree"=18, "Doctorate Degree"=20))
medical_raw_data$Education_numeric<-as.numeric(edu.num)
str(medical_raw_data)
medical_raw_data$Marital<-as.factor(medical_raw_data$Marital)
medical_raw_data$Area<-as.factor(medical_raw_data$Area)
medical_raw_data$Employment<-as.factor(medical_raw_data$Employment)
medical_raw_data$Gender<-as.factor(medical_raw_data$Gender)
medical_raw_data$ReAdmis<-as.factor(medical_raw_data$ReAdmis)
medical_raw_data$Soft_drink<-as.factor(medical_raw_data$Soft_drink)
medical_raw_data$Initial_admin<-as_factor(medical_raw_data$Initial_admin)
medical_raw_data$HighBlood<-as.factor(medical_raw_data$HighBlood)
medical_raw_data$Stroke<-as.factor(medical_raw_data$Stroke)
medical_raw_data$Arthritis<-as.factor(medical_raw_data$Arthritis)
medical_raw_data$Diabetes<-as.factor(medical_raw_data$Diabetes)
medical_raw_data$Hyperlipidemia<-as.factor(medical_raw_data$Hyperlipidemia)
medical_raw_data$Allergic_rhinitis<-as.factor(medical_raw_data$Allergic_rhinitis)
medical_raw_data$Reflux_esophagitis<-as.factor(medical_raw_data$Reflux_esophagitis)
medical_raw_data$Asthma<-as.factor(medical_raw_data$Asthma)
medical_raw_data$Services<-as.factor(medical_raw_data$Services)
str(medical_raw_data)
install.packages("psych")
library(psych)
install.packages("factoextra")
write.csv(medical_raw_data,"e:\\medical_raw_data.csv")